// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/health": {
            "get": {
                "description": "Проверка работоспособности сервиса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Healthcheck",
                "responses": {
                    "200": {
                        "description": "Сервис работает",
                        "schema": {
                            "$ref": "#/definitions/http.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/log/{log_id}": {
            "get": {
                "description": "Возвращает мета-информацию о логе (status, количество узлов/портов, дата загрузки)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Получение информации о логе",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID лога",
                        "name": "log_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Мета-информация о логе",
                        "schema": {
                            "$ref": "#/definitions/http.LogResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/node/{node_id}": {
            "get": {
                "description": "Возвращает детальную информацию об узле",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Получение информации об узле",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID узла",
                        "name": "node_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация об узле",
                        "schema": {
                            "$ref": "#/definitions/http.NodeResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/parse": {
            "post": {
                "description": "Выполняет парсинг логов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Парсинг логов",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"data/log.zip\"",
                        "description": "Путь",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Лог успешно обработан",
                        "schema": {
                            "$ref": "#/definitions/http.LogID"
                        }
                    },
                    "400": {
                        "description": "Неверный путь или path traversal",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Архив не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации: архив поврежден, неверный формат CSV, отсутствуют обязательные файлы, нет данных для сохранения",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "499": {
                        "description": "Клиент закрыл соединение",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/port/{node_id}": {
            "get": {
                "description": "Возвращает список портов указанного узла",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Получение портов узла",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID узла",
                        "name": "node_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Порты узла",
                        "schema": {
                            "$ref": "#/definitions/http.NodePortsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/topology/{log_id}": {
            "get": {
                "description": "Возвращает список узлов и групп топологии",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Получение топологии",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID лога",
                        "name": "log_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Топология",
                        "schema": {
                            "$ref": "#/definitions/http.TopologyResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "http.LogID": {
            "type": "object",
            "properties": {
                "log_id": {
                    "type": "integer"
                }
            }
        },
        "http.LogResponse": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "log_id": {
                    "type": "integer"
                },
                "nodes_count": {
                    "type": "integer"
                },
                "ports_count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "upload_date": {
                    "type": "string"
                }
            }
        },
        "http.NodePortData": {
            "type": "object",
            "properties": {
                "lid": {
                    "type": "integer"
                },
                "link_speed_actv": {
                    "type": "integer"
                },
                "link_width_actv": {
                    "type": "integer"
                },
                "port_guid": {
                    "type": "string"
                },
                "port_num": {
                    "type": "integer"
                },
                "port_state": {
                    "type": "integer"
                },
                "port_state_desc": {
                    "type": "string"
                }
            }
        },
        "http.NodePortsResponse": {
            "type": "object",
            "properties": {
                "node_guid": {
                    "type": "string"
                },
                "node_id": {
                    "type": "integer"
                },
                "ports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.NodePortData"
                    }
                }
            }
        },
        "http.NodeResponse": {
            "type": "object",
            "properties": {
                "endianness": {
                    "type": "integer"
                },
                "lid": {
                    "type": "integer"
                },
                "log_id": {
                    "type": "integer"
                },
                "node_desc": {
                    "type": "string"
                },
                "node_guid": {
                    "type": "string"
                },
                "node_id": {
                    "type": "integer"
                },
                "node_type": {
                    "type": "string"
                },
                "num_ports": {
                    "type": "integer"
                },
                "part_number": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "reproducibility_disable": {
                    "type": "integer"
                },
                "serial_number": {
                    "type": "string"
                }
            }
        },
        "http.TopologyEdge": {
            "type": "object",
            "properties": {
                "from_node_guid": {
                    "type": "string"
                },
                "from_port_num": {
                    "type": "integer"
                },
                "link_speed": {
                    "type": "integer"
                },
                "link_width": {
                    "type": "integer"
                },
                "to_node_guid": {
                    "type": "string"
                },
                "to_port_num": {
                    "type": "integer"
                }
            }
        },
        "http.TopologyGroup": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "group_name": {
                    "type": "string"
                },
                "node_guids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "http.TopologyNode": {
            "type": "object",
            "properties": {
                "lid": {
                    "type": "integer"
                },
                "node_desc": {
                    "type": "string"
                },
                "node_guid": {
                    "type": "string"
                },
                "node_id": {
                    "type": "integer"
                },
                "node_type": {
                    "type": "string"
                },
                "num_ports": {
                    "type": "integer"
                },
                "product_name": {
                    "type": "string"
                }
            }
        },
        "http.TopologyResponse": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.TopologyEdge"
                    }
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.TopologyGroup"
                    }
                },
                "log_id": {
                    "type": "integer"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.TopologyNode"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Yadro Netlog Parser",
	Description:      "API для работы логами",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
